version: '3'

services:
  mongodb:
    container_name: sales-db
    image: mongo:8.0.0-rc4
    restart: always
    environment:
      MONGO_INITDB_DATABASE: sales-db
    ports:
      - "27017:27017"
    volumes:
      - sales_db:/data/db

  sales_rabbit:
  image: rabbitmq:3-management
  container_name: sales_rabbit
  hostname: sales_rabbit
  networks:
    - sales-network
  ports:
    - 5672:5672
    - 25676:25676
    - 15672:15672
  environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest

  sales-api:
  build: './sales-api'
  container_name: sales-api
  depends_on:
    - sales-db
    - sales_rabbit
    - product-api
  networks:
    - sales-network
  environment:
    - PORT=3002
    - API_SECRET=YXV0aC1hcGktc2VjcmV0LWNvbnRhaW5lci0xMjM0NTY=
    - MONGO_DB_URL=mongodb://admin:123456@sales-db:27017/
    - RABBIT_MQ_URL=amqp://guest:guest@sales_rabbit:5672/
    - PRODUCT_API_URL=http://product-api:8081/api/product
    - NODE_ENV=container
  ports:
    - 3002:3002

volumes:
  sales_db:
    driver: local
